### ISSUE TITLE
Orchestrator: deployment check attempts template not working

### ISSUE THREAD

**Issue by sukrit007** [totem/totem.github.io#26]
**Given**: Deployment with check attempts using template

``` yaml
deployers:
  default:
    deployment:
      check:
        attempts: "{{ check_attempts}}"
```

**When**: I deploy the deployment using orchestrator

**Then**: Deploy fails due to number validation error.

**Expected**: Orchestrator should have converted the string values to number
